# Generated by Django 4.1.6 on 2023-02-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
