# Generated by Django 4.1.6 on 2023-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_other_user_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='other',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='mainsite.product'),
        ),
    ]
