# Generated by Django 4.1.6 on 2023-03-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=60)),
                ('comment', models.CharField(max_length=50)),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='UploadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('bio', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name', 'bio'],
            },
        ),
    ]
